In [21]:
import pandas as pd
import numpy as np

In [22]:
from_path = "../data/VDJdb/fitted_data/vdjdb_fitted_data_beta.tsv"
vdjdb_fitted_beta_df = pd.read_csv(from_path, sep="\t")
vdjdb_fitted_beta_df.columns

Index(['TCR_name', 'Gene', 'TRB_CDR3', 'TRBV', 'TRBJ', 'Species', 'MHC A',
       'MHC B', 'MHC class', 'Epitope', 'Epitope gene', 'Epitope species',
       'Reference', 'Method', 'Meta', 'CDR3fix', 'Score'],
      dtype='object')

In [23]:

for new_column in ['TRAV', 'TRAJ', 'TRA_CDR3','TRA_leader', 'TRB_leader', 'TRAC', 'TRBC', 'Linker', 
                   'Link_order', 'TRA_5_prime_seq', 'TRA_3_prime_seq', 'TRB_5_prime_seq', 'TRB_3_prime_seq']:
    vdjdb_fitted_beta_df[new_column] = np.nan 

template_columns_order = [
    'TCR_name', 'TRAV', 'TRAJ', 'TRA_CDR3', 'TRBV', 'TRBJ', 'TRB_CDR3',
    'TRAC', 'TRBC', 'TRA_leader', 'TRB_leader', 'Linker', 'Link_order',
    'TRA_5_prime_seq', 'TRA_3_prime_seq', 'TRB_5_prime_seq', 'TRB_3_prime_seq'
]

vdjdb_beta_schema_df = vdjdb_fitted_beta_df[template_columns_order]
vdjdb_beta_schema_df

,TCR_name,TRAV,TRAJ,TRA_CDR3,TRBV,TRBJ,TRB_CDR3,TRAC,TRBC,TRA_leader,TRB_leader,Linker,Link_order,TRA_5_prime_seq,TRA_3_prime_seq,TRB_5_prime_seq,TRB_3_prime_seq
0,1,NaN,NaN,NaN,TRBV13*01,TRBJ1-5*01,CASSYLPGQGDHYSNQPQHF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0,NaN,NaN,NaN,TRBV13*01,TRBJ1-5*01,CASSFEAGQGFFSNQPQHF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,NaN,NaN,NaN,TRBV13*01,TRBJ1-5*01,CASSFEPGQGFYSNQPQHF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,NaN,NaN,NaN,TRBV13*01,TRBJ1-5*01,CASSYEPGQVSHYSNQPQHF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,NaN,NaN,NaN,TRBV14*01,TRBJ2-1*01,CASSALASLNEQFF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49037,30590,NaN,NaN,NaN,TRBV7-2*01,TRBJ2-3*01,CASSVRSTDTQYF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49038,30591,NaN,NaN,NaN,TRBV7-2*01,TRBJ2-3*01,CASSLRYTDTQYF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49039,30592,NaN,NaN,NaN,TRBV7-3*01,TRBJ2-1*01,CASSPGQGGDNEQFF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49040,30593,NaN,NaN,NaN,TRBV5-1*01,TRBJ2-5*01,CASSLGAGGQETQYF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49041,30594,NaN,NaN,NaN,TRBV11-2*01,TRBJ2-5*01,CASSSTAQETQYF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
vdjdb_beta_cleaned_df = pd.concat([vdjdb_beta_schema_df, vdjdb_fitted_beta_df["Epitope"]], axis=1)
vdjdb_beta_cleaned_df

,TCR_name,TRAV,TRAJ,TRA_CDR3,TRBV,TRBJ,TRB_CDR3,TRAC,TRBC,TRA_leader,TRB_leader,Linker,Link_order,TRA_5_prime_seq,TRA_3_prime_seq,TRB_5_prime_seq,TRB_3_prime_seq,Epitope
0,1,NaN,NaN,NaN,TRBV13*01,TRBJ1-5*01,CASSYLPGQGDHYSNQPQHF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FLKEKGGL
1,0,NaN,NaN,NaN,TRBV13*01,TRBJ1-5*01,CASSFEAGQGFFSNQPQHF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FLKEKGGL
2,2,NaN,NaN,NaN,TRBV13*01,TRBJ1-5*01,CASSFEPGQGFYSNQPQHF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FLKEKGGL
3,3,NaN,NaN,NaN,TRBV13*01,TRBJ1-5*01,CASSYEPGQVSHYSNQPQHF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FLKEKGGL
4,4,NaN,NaN,NaN,TRBV14*01,TRBJ2-1*01,CASSALASLNEQFF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FLKEKGGL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49037,30590,NaN,NaN,NaN,TRBV7-2*01,TRBJ2-3*01,CASSVRSTDTQYF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PQPELPYPQPQL
49038,30591,NaN,NaN,NaN,TRBV7-2*01,TRBJ2-3*01,CASSLRYTDTQYF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PQPELPYPQPQL
49039,30592,NaN,NaN,NaN,TRBV7-3*01,TRBJ2-1*01,CASSPGQGGDNEQFF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PQQPFPQPEQPFP
49040,30593,NaN,NaN,NaN,TRBV5-1*01,TRBJ2-5*01,CASSLGAGGQETQYF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PQQPFPQPEQPFP
49041,30594,NaN,NaN,NaN,TRBV11-2*01,TRBJ2-5*01,CASSSTAQETQYF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PQQPFPQPEQPFP

In [25]:
vdjdb_fitted_beta_df.rename(columns={"Score": "Score_TRB"}, inplace=True)
vdjdb_beta_cleaned_df["Score_TRA"] = np.nan
vdjdb_beta_cleaned_df["Score_TRB"] = vdjdb_fitted_beta_df["Score_TRB"]
vdjdb_beta_cleaned_df

,TCR_name,TRAV,TRAJ,TRA_CDR3,TRBV,TRBJ,TRB_CDR3,TRAC,TRBC,TRA_leader,TRB_leader,Linker,Link_order,TRA_5_prime_seq,TRA_3_prime_seq,TRB_5_prime_seq,TRB_3_prime_seq,Epitope,Score_TRA,Score_TRB
0,1,NaN,NaN,NaN,TRBV13*01,TRBJ1-5*01,CASSYLPGQGDHYSNQPQHF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FLKEKGGL,NaN,2
1,0,NaN,NaN,NaN,TRBV13*01,TRBJ1-5*01,CASSFEAGQGFFSNQPQHF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FLKEKGGL,NaN,2
2,2,NaN,NaN,NaN,TRBV13*01,TRBJ1-5*01,CASSFEPGQGFYSNQPQHF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FLKEKGGL,NaN,2
3,3,NaN,NaN,NaN,TRBV13*01,TRBJ1-5*01,CASSYEPGQVSHYSNQPQHF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FLKEKGGL,NaN,2
4,4,NaN,NaN,NaN,TRBV14*01,TRBJ2-1*01,CASSALASLNEQFF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FLKEKGGL,NaN,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49037,30590,NaN,NaN,NaN,TRBV7-2*01,TRBJ2-3*01,CASSVRSTDTQYF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PQPELPYPQPQL,NaN,0
49038,30591,NaN,NaN,NaN,TRBV7-2*01,TRBJ2-3*01,CASSLRYTDTQYF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PQPELPYPQPQL,NaN,0
49039,30592,NaN,NaN,NaN,TRBV7-3*01,TRBJ2-1*01,CASSPGQGGDNEQFF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PQQPFPQPEQPFP,NaN,0
49040,30593,NaN,NaN,NaN,TRBV5-1*01,TRBJ2-5*01,CASSLGAGGQETQYF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PQQPFPQPEQPFP,NaN,2
49041,30594,NaN,NaN,NaN,TRBV11-2*01,TRBJ2-5*01,CASSSTAQETQYF,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,PQQPFPQPEQPFP,NaN,0

In [ ]:
to_path = "../data/VDJdb/cleaned_data"
file_name = "vdjdb_cleaned_data_beta.tsv"
vdjdb_beta_cleaned_df.to_csv(to_path+"/"+file_name, sep="\t", index=False)